# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
