# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20171026_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.FileField(default=None, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
